---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: "{{ index .Values.annotations .Values.device "inferenceServiceLlmDisplayName" }}"
    serving.kserve.io/deploymentMode: RawDeployment
  name: "{{ index .Values.mainLLM .Values.device "name" }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      env:
        {{- range $name, $value := .Values.inferenceServiceLlm.common.env }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $name, $value := index .Values.inferenceServiceLlm .Values.device "env" }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
      resources:
        {{- toYaml (index .Values.inferenceServiceLlm .Values.device "resources") | nindent 8 }}
      runtime: "{{ index .Values.mainLLM .Values.device "name" }}"
      storageUri: "{{ .Values.mainLLM.storageUri }}"
      {{- if hasKey (index .Values.inferenceServiceLlm .Values.device) "volumeMounts" }}
      volumeMounts:
        {{- toYaml (index .Values.inferenceServiceLlm .Values.device "volumeMounts") | nindent 8 }}
      {{- end }}
  {{- if hasKey (index .Values.inferenceServiceLlm .Values.device) "volumes" }}
  volumes:
    {{- toYaml (index .Values.inferenceServiceLlm .Values.device "volumes") | nindent 4 }}
  {{- end }}