---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '{{ index .Values.annotations .Values.device "detectorsRecommendedAccelerators" | toJson }}'
    opendatahub.io/template-display-name: vLLM ServingRuntime for KServe
    opendatahub.io/template-name: vllm-runtime
    openshift.io/display-name: "{{ index .Values.mainLLM .Values.device "name" }}"
  name: "{{ index .Values.mainLLM .Values.device "name" }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    opendatahub.io/dashboard: "true"
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
    - args:
        {{- range .Values.servingRuntimeLlm.common.args }}
        - {{ . | quote }}
        {{- end }}
        {{- range index .Values.servingRuntimeLlm .Values.device "args" }}
        - {{ . | quote }}
        {{- end }}
      command:
        {{- range index .Values.servingRuntimeLlm .Values.device "command" }}
        - {{ . | quote }}
        {{- end }}
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: "{{ index .Values.mainLLM .Values.device "image" }}"
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
        {{- if eq .Values.device "cpu" }}
        - name: chat-template-volume
          mountPath: /app/data/template/tool_chat_template_llama3.2_json.jinja
          subPath: tool_chat_template_llama3.2_json.jinja
        {{- end }}
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  {{- with index .Values.mainLLM .Values.device "tolerations" }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
      {{- if eq .Values.device "cpu" }}
    - name: chat-template-volume
      configMap:
        name: chat-template
    {{- end }}